<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.8.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" Version="1.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing" Version="1.1.2" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0.0" />
    <!--<PackageReference Include="System.Formats.Asn1" Version="9.0.2" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analyzers\MicroUtils.HarmonyAnalyzers.csproj" />
    <ProjectReference Include="..\CodeFixes\MicroUtils.HarmonyAnalyzers.CodeFixes.csproj" />
    <ProjectReference Include="..\Completions\MicroUtils.HarmonyAnalyzers.Completions.csproj" />
  </ItemGroup>

</Project>
