<Project>
  <PropertyGroup>
    <VersionPrefix>1.6.1</VersionPrefix>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DevelopmentDependency>true</DevelopmentDependency>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-hh2w-p6rv-4g7w" />
    <NugetAuditSuppress Include="https://github.com/advisories/GHSA-8g4q-xg66-9fp4" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <VersionSuffix>debug-$([System.DateTimeOffset]::UtcNow.ToString(yyMMddHHmm))</VersionSuffix>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <!--<VersionSuffix>beta$([System.DateTimeOffset]::UtcNow.ToUnixTimeSeconds().ToString())</VersionSuffix>-->
    <!--<VersionSuffix>rc1</VersionSuffix>-->
  </PropertyGroup>
  
</Project>